### ISSUE TITLE
La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#1]
Primero, que la entendiste al revés: `Martes` viene después que `Lunes`, pero vos devolvés justo lo contrario.

Por otra parte, `Miercoles` viene después que `Lunes`, pero tu función (suponiendo que la invertimos), no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by amaliajaime** [comment]
Fidel, Cómo estás?

Si, claramente la entendía mal.
Con este si que estuve trabada... Se me había ocurrido en un principio con los días del extremo hacer PM, porque por ejrmplo si me llega un día cualquiera, y Lunes no me importa cuál sea, que siempre sería True a menos de que sea si mismo, con el Martes me pasaba algo similar, si es me llega un Lunes y Martes era True porque era el único día que estaba delante, los demás casos todos False, excepto si mismo.
Bueno, pero no era muy feliz para los casos del medio, miércoles, jueves, y viernes. Esos pensaba hacerlos con una función, pero igual se incrementaban la cantidad de casos.
Así que se me termino ocurriendo de esta forma después de charlar con compas, y que me digan que con PM los casos igual  crecían por la combinatoria de casos y dije -Bueno capaz que con Pm no va-. 

Saludos,

**Comment by fidel-ml** [comment]
Ojo con el nombre de la función que transforma días a números... Dice `evaludarDia`, y supongo que quisiste poner `evaluarDia`. Igual, sería mejor algo como `diaAInt` que indique que es una transformación...
