### ISSUE TITLE
Pr2: en `losMenoresA` no se quitan los mayores a `n`, sino que se reemplazan por 0

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#10]
El enunciado pide eliminar los mayores a `n`, pero vos los estás reemplazando por 0. Eso NO es correcto, pues en el resultado hay elementos que no existían en la lista original

**Comment by amaliajaime** [comment]
Fidel, 
buenas tardes.

Corregí el issue.

Saludos,
