### ISSUE TITLE
Pr2: en la función `reversa` estás siendo redundante en forma innecesaria

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#13]
Estás usando `(++)` y también `agregarAlFinal`, pero solamente deberías utilizar una de ellas. En particular, en este caso, el `agregarAlFinal [] x` es exactamente lo mismo que `[x]` y entonces no haría falta... (y también podés no utilizar `(++)` y utilizar `agregarAlFinal` para agregar `x` a la lista reversa de la cola...

**Comment by amaliajaime** [comment]
Fidel,
buenas tardes.

Corregí este issue.

Saludos,
