### ISSUE TITLE
Pr2: ATENCION a los paréntesis

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#17]
NO se colocan paréntesis alrededor de elementos solos. O sea, es incorrecto escribir `f (x)`, porque `f x` dice exactamente lo mismo.
Lo hacés por ejemplo en `cantPokemonDe`, y también lo marqué en la práctica 1...

**Comment by amaliajaime** [comment]
Fidel,
Buenas tardes.

Corregí el issue.

Saludos,
