### ISSUE TITLE
Pr2: la función `mismoTipo` tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#18]
OJO: este error ya te lo había marcado en la práctica 1. TENÉS que acordarte las cosas que vas corrigiendo, para no volver a cometer los mismos errores. Hay mucho para aprender, y si cada vez hay que volver a marcar todo, entonces se complica a medida que avanzamos...

**Comment by amaliajaime** [comment]
Fidel,

Si, tenés razón, estaba pensando de la misma forma que antes.
Corregido, gracias!

**Comment by fidel-ml** [comment]
Pero agregaste la función "mismoTipoInt" que básicamente hace lo mismo que antes... O sea, la idea es que NO tengas una función que pregunte por algo específico y luego lo vuelva número, sino que tengas una función que vuelva número a cualquier pregunta, y la uses (sin tener que definir `mismoTipoInt`).

**Comment by amaliajaime** [comment]
Fidel, buen día
Corregí la función **mismoTipoInt**
Me di cuenta a qué te referís con tener una función que devuelva número a cualquier pregunta, o eso espero.

Saludos,
