### ISSUE TITLE
Hay "miedo al booleano" en la función or 

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#2]
En la función `or` estás haciendo una versión con pattern matching del "miedo al booleano".
Básicamente, preguntás si algo es `True` para devolver `True` y cuando no es `True` devolvés `False`. Está escondida debido al uso de guiones bajos sin pensar demasiado... :-D
Básicamente, es como si tuvieses `if b==True then True else False`, que es exactamente lo mismo que `b`.

**Comment by amaliajaime** [comment]
Siiiii en este te lo confirmo.
Lo mismo, me rompió la cabeza, no pude pensarlo, charlando con compas lo fui sacando y después me explicaron lo que diste en clase.
En pensar el caso False, y después se cubría solo el caso que llegará después.

Saludos,

**Comment by fidel-ml** [comment]
Fijate que igual dejaste un caso innecesario al final, porque nunca se alcanza...

**Comment by amaliajaime** [comment]
Si, me quedó de la versión anterior por lo que veo.
Listo, ya lo arregle.

Gracias.

**Comment by amaliajaime** [comment]
Perdón!!
Corregido de nuevo, estoy pisando cambios a lo loco.
Pero ya lo arrgle.

Saludos,
