### ISSUE TITLE
Pr2: en `cuentaRegresiva` no tenés en cuenta los valores negativos

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#20]
El enunciado pide explícitamente que se contemplen, pues establece que NO debe ser un error. Así como está definida, los números negativos se cuelgan.

**Comment by amaliajaime** [comment]
Fidel, 

Corregí el issue.
Saludos!

**Comment by amaliajaime** [comment]
Fidel, buen día.

Este issue fue corregido. Indícame si sigue estando mal.

Gracias!

**Comment by fidel-ml** [comment]
No está mal. Pero ahora podrías juntar los casos de 0 y negativos, porque si no estás haciendo 2 preguntas cada vez...

**Comment by amaliajaime** [comment]
Fidel,
Corregido.

Saludos,
