### ISSUE TITLE
Pr2: en `losQueLeGanan` estás haciendo doble PM y usando recursión sobre estructuras NO recursivas

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#21]
Si una estructura no es recursiva, NO uses recursión. Cuando un registro contiene una lista, y tenés que procesar esa lista, definís una función auxiliar sobre listas, y NO hacés recursión sobre el registro. El llamado recursivo que hacés de esta función en el 3er caso es grave, porque tenés que armar una estructura que carece de sentido para el problema (es un entrenador con menos Pokémon; solamente tenés que volver a poner el constructor de entrenador porque estás usando la herramienta incorrecta...)

**Comment by amaliajaime** [comment]
Fidel,
Corregí este error.

Saludos,

**Comment by amaliajaime** [comment]
Fidel, 

Corrijo nuevamente el ejercicio.

Saludos,

**Comment by fidel-ml** [comment]
Sigue siendo incorrecto. La función `leGanaPorTipo` sigue haciendo doble PM. NO TENÉS que mirar los dos parámetros A MENOS que el problema lo requiera (y no es este el caso). Tenés que aprender a aplicar la recursión estructural, ya que de eso se trata esta práctica. No tenés que pensar cómo mejorar o cuántos casos hay antes de entender si sale o no por recursión estructural...

Por otra parte, estás controlando que peleen el 1ero con el 1ero, el 2do con el 2do, etc. Pero NO es lo que pide el enunciado...

**Comment by amaliajaime** [comment]
Fidel, 
Cómo estás? Lo estuve pensando de otra manera.
Espero haber hecho bien la recursión.

Saludos,

**Comment by fidel-ml** [comment]
Ahora cambiaste el código de forma de que estás usando cosas que no deberías... Mirá #22

**Comment by amaliajaime** [comment]
Fidel,
Buenas tardes.

Corregí este issue.
Saludos,

**Comment by fidel-ml** [comment]
Seguís teniendo el mismo problema que te contesté en #22

**Comment by amaliajaime** [comment]
Fidel,
Relacionado con el Issue #22 , corregí esta función, espero haber comprendido las correcciones que mencionas.

Saludos,

**Comment by fidel-ml** [comment]
Ahora está mejor. Se suponía que le ganaba a todos, pero no es lo importante.
También podrías utilizar el `contarTrue` para sacar el if-then-else, pero es un detalle.

**Comment by amaliajaime** [comment]
Es verdad, lo acabo de notar!! 
No lo había pensado así.

Gracias x mencionarlo!
