### ISSUE TITLE
Pr2: la función `sumaSiSupera` es prácticamente idéntica a `mismoTipoInt`, porque ambas tienen más responsabilidades de las que deberían

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#22]
Fijate el issue #18, porque es el mismo problema.
Si te encontrás escribiendo cosas parecidas una y otra vez, fijate mejor porque estás frente a un caso de subtarea escondida que podrías haber aprovechado...

**Comment by fidel-ml** [comment]
Por otra parte, su nombre es extremadamente infeliz, porque no suma nada.

**Comment by amaliajaime** [comment]
Fidel,
Corregí el nombre.

Saludos,

**Comment by fidel-ml** [comment]
Peor no es solamente corregir el nombre... `unoSiSupera` sigue teniendo demasiadas responsabilidades (está duplicando trabajo que YA hace `contarTrue`, por ejemplo).

**Comment by amaliajaime** [comment]
Fidel, si, encontré lo que me mencionaste.

Corregí la función.
Saludos,

**Comment by fidel-ml** [comment]
Ahora estás usando la forma en que sabés que se resuelven las peleas para hacer este código, en lugar de DELEGAR esta tarea en la función correspondiente (que hicimos en la Práctica 1). NO es adecuado, porque si se cambia la forma de pelear, tu función deja de servir cuando no debería.

**Comment by amaliajaime** [comment]
Fidel, 

Corregí lo mencionado. 
Me indicas si lo estoy entendiendo?

Gracias,

**Comment by fidel-ml** [comment]
Mucho mejor. Pero ahora `mismoTipo t (tipoDePokemon p1)` lo estás controlando CADA vez que pelea, PARA CADA pelea, en lugar de controrarlo antes. Básicamente, si no tiene ese tipo, ni siquiera considera ninguna pelea...

**Comment by amaliajaime** [comment]
Fidel,
Si entiendo lo debía limitar antes para no trabajar de más en cada pelea a evaluar.
Corregido, gracias!!!

**Comment by fidel-ml** [comment]
Mejora, pero ahora no contás los pokémon que ganan, sino las veces que ganan...
Revisá bien qué contás, y qué tenés que preguntar...

**Comment by amaliajaime** [comment]
Fidel,
Buenas tardes.

Si, ejecutando la funcion noté lo que mencionas! No contaba ganador, sino ganadas...
Bueno, ahí va de nuevo la corrección.

Gracias!!
