### ISSUE TITLE
Pr 2: en `proyectosSinRepetidos` estás mirando la pertenencia contra una lista más larga de lo necesaria

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#24]
Al usar `ps` en lugar de `proyectosSinRepetidos ps` en la condición, mirás más veces de las necesarias.
Esto es en general para cuando querés remover duplicados...

**Comment by amaliajaime** [comment]
Fidel, no me queda en claro esta ayuda que me das.
No estoy viendo en dónde utilizar **proyectosSinRepetidos ps**

Gracias,

**Comment by fidel-ml** [comment]
Cuando preguntás si `x` pertenece a la lista de nombre de los proyectos en `ps`,  esa lista `ps` puede tener muchos repetidos. Pero vos tenés que calcular una versión de esa lista SIN repetidos, con lo cual podrías preguntar contra esa y sería más eficiente.

Por otra parte, en la clase vimos cómo pensar esto mediante recursión estructural y subtareas para no cometer ese error... Es importante que prestes atención a las cosas que se dicen en clase.

**Comment by amaliajaime** [comment]
Fidel, 
Buenas tardes.

Corregi este issue.
Saludos,

**Comment by amaliajaime** [comment]
Fidel, 
Cómo estás?
Acabo de corregir y repensar las funciones para este punto.

Saludos,

**Comment by fidel-ml** [comment]
Muchísimo mejor. Ahora estás haciendo dos llamados recursivos, que podrías hacer una sola vez si usases una subtarea para la decisión de agregar o no...

**Comment by amaliajaime** [comment]
Fidel, buen día.
Ayer lo pude comprender mejor con la ayuda de Ornella.

Saludos,
