### ISSUE TITLE
Pr2: en `sumarDevSr` está de más sumar 0

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#25]
Nunca se escribe `0+x` porque es lo mismo que escribir `x`. ¿Para qué escribís ese `0+...`?
Además, podrías aprovechar algunas de las funciones que definiste en otros lados para evitar usar un if acá...

**Comment by amaliajaime** [comment]
Fidel, buenas tardes.
Corregí el issue que me marcaste.

Saludos,
