### ISSUE TITLE
Pr2: la función `asignadosPorProyecto` recorre la empresa muchas veces

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#26]
Si usás recursión estructural en lugar de 400 subtareas, sale con mucho menos esfuerzo...

**Comment by amaliajaime** [comment]
Fidel,
Cómo estás?
Corregí esta función.

Saludos,

**Comment by fidel-ml** [comment]
Está mucho mejor, pero el if-then-else que hacés para mirar si está es innecesario, ya que si no está la otra función también lo agrega con el mismo valor...

**Comment by amaliajaime** [comment]
Fidel,
Cómo estás?
Entendido, cambie lo que me mencionas.

Saludos,

**Comment by fidel-ml** [comment]
¡Bien!
