### ISSUE TITLE
Pr3: `ponerN` no está hecha por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#27]
En este caso es lo mismo. Pero si seguís esta forma de hacerlo, en otros casos se puede complicar mucho.
Siempre es mejor probar primero recursión estructural.
Para ser estructural, el llamado recursivo puede ir SOLAMENTE sobre las partes recursivas.

**Comment by amaliajaime** [comment]
Fidel, 
Cómo estás?

Subí la corrección de este ejercicio.

Saludos,
