### ISSUE TITLE
Pr3: `hayTesoro` y `esTesoro` tienen miedo al booleano

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#28]
NUNCA deberías usar un if-then-else para devolver booleanos. Esto es señal de miedo al booleano.
Pensá qué operación es la que tenés que usar, en lugar de pensar en cómo elegir la opción...

**Comment by amaliajaime** [comment]
Fidel,
Lo corregí nuevamente.

Saludos!

**Comment by fidel-ml** [comment]
Ahora lo sigue teniendo `hayTesoroEn`... TODA VEZ que uses if-then-else para devolver un booleano, sospechá que hay mejores formas de hacerlo...

**Comment by amaliajaime** [comment]
Fidel,
Corregí el issue que me marcaste.

Saludos,
