### ISSUE TITLE
Pr3: el tipo `Objeto` NO DEBERÍA ser instancia de `Eq`

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#29]
NO ESTÁ PERMITIDO usar `Eq` en esta materia, SALVO que lo indiquemos los docentes o sea un tipo predefinido (`Int`, `String`, etc.).
La idea es que escriban su propio código, y no que ese código se los arme una máquina sin saber qué hace...

**Comment by amaliajaime** [comment]
Fidel, corregí este Issue.

Saludos,
