### ISSUE TITLE
Pr3: `sumarSiT` tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#32]
Esto es algo que trabajamos en la práctica 2... No hay que hacer funciones que se puedan expresar como combinación de otras más sencillas, en general.

**Comment by amaliajaime** [comment]
Fidel,
Corregí ete issue.

Saludos,

**Comment by fidel-ml** [comment]
Yo lo sigo viendo igual... Pregunta algo específico, y TAMBIÉN transforma el booleano resultante en un número,
En InPr vieron cómo mejorar eso con subtareas. y lo usamos también en las prácticas 1 y 2... Hay que prestar atención para aprender cosas que van a servir siempre...

**Comment by amaliajaime** [comment]
Fidel, 

Si, entendí lo que me mencionas.
Lo corregí.

Saludos,
