### ISSUE TITLE
Pr1: en el caso de `superaA` estás haciendo doble pattern matching

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#5]
No es feliz hacer doble PM salvo que sea imposible hacer la función de otra manera.
En este caso, estás mirando al mismo tiempo un `Pokemon` y su `TipoDePokemon`. Lo adecuado sería que la función que trabaja sobre `Pokemon` no mire los tipos, y que exista una subtarea que se encargue de mirar los tipos...

**Comment by amaliajaime** [comment]
Buenas!

Vuelvo a corregir la función.

Saludos,

**Comment by fidel-ml** [comment]
Fijate que ahora estás llamando a `tipoDePokemon (K t1 e)` que es exactamente lo mismo que `t1`. O bien usás pattern matching para `K` y directamente usás `t1`, o bien usás `tipoDePokemon` y NO hacés PM sobre `K`.

**Comment by amaliajaime** [comment]
Fidel, 
Vuelvo a corregir el ejercicio.

Saludos,
