### ISSUE TITLE
Pr1: la función `contarPolemonSi` mezcla niveles y tiene varias responsabilidades

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#6]
Es bueno que cada subtarea tenga una única responsabilidad. En este caso tu función tiene 3:
  - accede a un pokemon para obtener su tipo
  - compara dos tipos para ver si son o no el mismo
  - transforma el resultado de la comparación en un valor numérico para poderlo sumar
 
Cada una de esas responsabilidades debería ser expresada por una subtarea diferente

**Comment by amaliajaime** [comment]
Fidel, cómo estás?

Acá tengo dudas, acabo de realizar la función nuevamente separando por responsabilidades.
Cuando quiero contar Pokemons x ejemplo de Agua, y el Entrenador solo tiene de tipo Agua va bien, pero si tiene 2 de distintos tipos me da un error.

El error es el siguiente:
Program error: pattern match failure: esMismoTipo TipoDePokemon_Fuego (tipoDePokemon (Pokemon_K TipoDePokemon_Planta (Num_fromInt instNum_v30 1)))

Entiendo que falla el PM, pero no veo por qué?
No puedo descubrir a qué se debe.

Gracias,

**Comment by fidel-ml** [comment]
Ese error quiere decir que te faltan casos...
El problema es que no todas las líneas que escribiste tienen el mismo nombre. Fijate que la última se llama diferente, y entonces no la considera parte de tu definición, sino de OTRA función...

**Comment by amaliajaime** [comment]
Fidel, 
Buenas,
Ya corregí este error.

Gracias,
