### ISSUE TITLE
Pr1: en varias funciones (por ejemplo, `superaA` y `cantidadDePokemon`) estás haciendo PM innecesario

### ISSUE THREAD

**Issue by fidel-ml** [amaliajaime/EstrD22s1#9]
Solamente hay que hacer PM cuando querés acceder a las partes o validar que algo está hecho con determinado constructor. No tiene sentido hacer PM para luego usarlo exactamente igual del otro lado. Por ejemplo:
`cantidadDePokemonDe tipoPokemon (E n p1 p2) = contarPokemonSi (tipoPokemon) (pokemonsPorEntrenador (E n p1 p2))`
es exactamente lo mismo que
`cantidadDePokemonDe tipoPokemon e = contarPokemonSi (tipoPokemon) (pokemonsPorEntrenador e)`

Es una mala práctica usar herramientas que no necesitás.

**Comment by amaliajaime** [comment]
Fidel,
Si, entiendo lo que me marcas.
Corregí este issue, si no estoy captando la idea y sigue estando mal te lo consulto mañana también!!

Gracias!!
